# This file is used to create and configure simulated DotBot instances for the simulator.
# It is only used when the flag `-p dotbot-simulator` is set, otherwise it is ignored.

[[dotbots]]
address = "AAAAAAAA11111111" # DotBot unique address
calibrated = true # optional, defaults to true
pos_x = 400_000 # [0, 1_000_000]
pos_y = 400_000 # [0, 1_000_000]
theta = 0.0 # [0.0, 2pi]

[[dotbots]]
address = "AAAAAAAA22222222"
pos_x = 600_000
pos_y = 400_000
theta = 1.57

# [[dotbots]]
# address = "AAAAAAAA33333333"
# pos_x = 600_000
# pos_y = 600_000
# theta = 3.14

# [[dotbots]]
# address = "AAAAAAAA44444444"
# pos_x = 400_000
# pos_y = 600_000
# theta = 4.71

[[dotbots]]
address = "FFFFFFFF00000000"
pos_x = 500_000
pos_y = 500_000
theta = 0.0

[[dotbots]]
address = "FFFFFFFF00000001"
pos_x = 450_000
pos_y = 400_000
theta = 0.0

[[dotbots]]
address = "FFFFFFFF00000002"
pos_x = 550_000
pos_y = 400_000
theta = 1.57